#!name=去开屏广告
#!desc=去除一些自用软件的开屏广告

[URL Rewrite]
^https?:\/\/api\.douban\.com\/v\d\/app_ads\/ - reject
^https?:\/\/api\.douban\.com\/b.*\/common_ads\?.* url reject-dict
^https?:\/\/img\d\.doubanio\.com\/view\/dale-online\/dale_ad\/ url reject
^https?:\/\/frodo\.douban\.com\/api\/v2\/movie\/banner url reject
^https?:\/\/erebor\.douban\.com\/count\/\?ad= url reject
[MITM]
hostname = %APPEND% api.douban.com,img*.douban.com,frodo.douban.com,erebor.douban.com
