#!name=App&小程序净化合集
#!desc=去除一些冗余的模块，遇到异常时关闭此配置

# > 滴滴出行 微信小程序个人中心净化
^https:\/\/common\.diditaxi\.com\.cn\/common\/v5 url script-response-body https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/didi/didiAds.js
^https:\/\/conf\.diditaxi\.com\.cn\/homepage\/v1\/core url reject-dict

# > 蜜雪冰城 微信小程序净化
^https:\/\/mxsa\.mxbc\.net\/api\/v1\/adinfo\/adplace\/query url reject-dict

# > 携程旅行 微信小程序净化
^https:\/\/m\.ctrip\.com\/restapi\/soa2\/12673\/queryWeChatHotEvent url reject-dict
^https:\/\/m\.ctrip\.com\/restapi\/soa2\/13012\/getWaterflowInfo url script-response-body https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/T3.js
^https:\/\/m\.ctrip\.com\/restapi\/soa2\/13916\/tripAds url reject-dict

hostname = %APPEND% common.diditaxi.com.cn, conf.diditaxi.com.cn, mxsa.mxbc.net
