#!name=小程序净化合集
#!desc=去除一些冗余的模块，遇到异常时关闭此配置

[Rewrite]
# 微信小程序通用规则
DOMAIN, wxsmsdy.video.qq.com, REJECT
DOMAIN, wxsnsdy.wxs.qq.com, REJECT
DOMAIN, wxsnsdythumb.wxs.qq.com, REJECT

# 收钱吧广告
DOMAIN, ads-shopping.shouqianba.com, REJECT

# 收钱吧小程序
^https:\/\/api\.pinduoduo\.com\/api\/ktt_gateway\/activity\/feeds\/personal_home_page\/ reject

# 滴滴出行 微信小程序个人中心净化
^https:\/\/common\.diditaxi\.com\.cn\/common\/v5 url script-response-body https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/didi/didiAds.js
^https:\/\/conf\.diditaxi\.com\.cn\/homepage\/v1\/core url reject-dict

# 蜜雪冰城 微信小程序净化
^https:\/\/mxsa\.mxbc\.net\/api\/v1\/adinfo\/adplace\/query url reject-dict

# 携程旅行 微信小程序净化
^https:\/\/m\.ctrip\.com\/restapi\/soa2\/12673\/queryWeChatHotEvent url reject-dict
^https:\/\/m\.ctrip\.com\/restapi\/soa2\/13012\/getWaterflowInfo url script-response-body https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/T3.js
^https:\/\/m\.ctrip\.com\/restapi\/soa2\/13916\/tripAds url reject-dict

# 申通快递
^https:\/\/customer-app\.sto\.cn\/api\/app\/banner\/banner reject-dict
^https:\/\/sto-customer-app\.oss-cn-shanghai\.aliyuncs\.com\/images reject-dict

# 顺丰速运+
^https:\/\/ucmp\.sf-express\.com\/proxy\/esgcempcore\/memberGoods\/pointMallService\/goodsList reject-dict
^https:\/\/ucmp\.sf-express\.com\/proxy\/operation-platform\/info-flow-adver\/query reject-dict

# 中通快递
^https:\/\/fscdn\.zto\.com\/fs1 reject
^https:\/\/hdgateway\.zto\.com\/getAdInfo reject
^https:\/\/hdgateway\.zto\.com\/getApolloConfig reject
^https:\/\/hdgateway\.zto\.com\/listJumperShow reject
^https:\/\/hdgateway\.zto\.com\/track reject

[MitM]
hostname = %APPEND% ads-shopping.shouqianba.com, api.pinduoduo.com, common.diditaxi.com.cn, conf.diditaxi.com.cn, customer-app.sto.cn, fscdn.zto.com, hdgateway.zto.com, m.ctrip.com, mxsa.mxbc.net, sto-customer-app.oss-cn-shanghai.aliyuncs.com, ucmp.sf-express.com